vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    ressource_thumbnail:
      uri_prefix: /images/ressources
      upload_destination: "%kernel.project_dir%/public/images/ressources"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
